config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
	namespace :admin do
		resources :shops
		resources :users
		resources :store_settings
		root to: "shops#index"
	end
	devise_for :users
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!

    def authenticate_admin
      if current_user.role == "admin"
        return true
      else
        redirect_to admin_shops_path
      end
    end
      # TODO Add authentication logic here.

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <%#= link_to(t("administrate.navigation.back_to_app"), root_url, class: "button button--alt") if defined?(root_url) %>
	<% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
  	<% if current_user.role != "sub_admin" %>
		  <% if resource != "store_settings" %>
		    <%= link_to(
		      display_resource_name(resource),
		      resource_index_route(resource),
		      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
		    ) if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource)) %>
		  <% end %>
		<% end %>
	<% end %>

<%= link_to "Log out", destroy_session_path(current_user), method: "delete",class: "button button--alt"%>
</nav>